FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY coordinator /app/coordinator
COPY shared /app/shared

CMD ["uvicorn", "coordinator.main:app", "--host", "0.0.0.0", "--port", "8000"]