services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    container_name: coordinator
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_QUEUE_NAME=jobs
      - COORDINATOR_DB_PATH=/app/results/coordinator.db
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./results:/app/results
      - ./dataset:/app/dataset

  worker_1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_QUEUE_NAME=jobs
      - WORKER_QUEUES=jobs
      - WORKER_ID=worker-1
    depends_on:
      - redis
    volumes:
      - ./results:/app/results
      - ./dataset:/app/dataset

  worker_2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_QUEUE_NAME=jobs
      - WORKER_QUEUES=jobs
      - WORKER_ID=worker-2
    depends_on:
      - redis
    volumes:
      - ./results:/app/results
      - ./dataset:/app/dataset

  worker_3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_QUEUE_NAME=jobs
      - WORKER_QUEUES=jobs
      - WORKER_ID=worker-3
    depends_on:
      - redis
    volumes:
      - ./results:/app/results
      - ./dataset:/app/dataset
