services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    container_name: coordinator
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_QUEUE_HIGH_NAME=jobs_high
      - JOB_QUEUE_NORMAL_NAME=jobs_normal
      - JOB_QUEUE_LOW_NAME=jobs_low
      - JOB_PRIORITY_HIGH_MAX=3
      - JOB_PRIORITY_NORMAL_MAX=7
      - COORDINATOR_DB_PATH=/app/results/coordinator.db
      - JOB_TIMEOUT_SECONDS=300
      - JOB_MAX_RETRIES=2
      - JOB_RETRY_INTERVAL_SECONDS=15
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./results:/app/results
      - ./dataset:/app/dataset
      - ./docs:/app/docs
      - ./scripts:/app/scripts

  worker_1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_QUEUE_HIGH_NAME=jobs_high
      - JOB_QUEUE_NORMAL_NAME=jobs_normal
      - JOB_QUEUE_LOW_NAME=jobs_low
      - WORKER_QUEUES=jobs_high,jobs_normal,jobs_low
      - WORKER_ID=worker-1
      - WORKER_PROCESS_TIMEOUT_SECONDS=240
    depends_on:
      - redis
    volumes:
      - ./results:/app/results
      - ./dataset:/app/dataset
      - ./docs:/app/docs
      - ./scripts:/app/scripts

  worker_2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_QUEUE_HIGH_NAME=jobs_high
      - JOB_QUEUE_NORMAL_NAME=jobs_normal
      - JOB_QUEUE_LOW_NAME=jobs_low
      - WORKER_QUEUES=jobs_high,jobs_normal,jobs_low
      - WORKER_ID=worker-2
      - WORKER_PROCESS_TIMEOUT_SECONDS=240
    depends_on:
      - redis
    volumes:
      - ./results:/app/results
      - ./dataset:/app/dataset
      - ./docs:/app/docs
      - ./scripts:/app/scripts

  worker_3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JOB_QUEUE_HIGH_NAME=jobs_high
      - JOB_QUEUE_NORMAL_NAME=jobs_normal
      - JOB_QUEUE_LOW_NAME=jobs_low
      - WORKER_QUEUES=jobs_high,jobs_normal,jobs_low
      - WORKER_ID=worker-3
      - WORKER_PROCESS_TIMEOUT_SECONDS=240
    depends_on:
      - redis
    volumes:
      - ./results:/app/results
      - ./dataset:/app/dataset
      - ./docs:/app/docs
      - ./scripts:/app/scripts
